---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: influxdb-release

outputs:
  - name: release

run:
  path: influxdb-release/ci/tasks/create-candidate.sh
